version: '3.4'

services:

  publisher-service:
    build:
      context: .
      dockerfile: PublisherService/Dockerfile
    image: publisher-service
    container_name: publisher-service
    networks:
      - rabbitmq
      - kafka
    ports:
      - 9000:80
      - 9100:443

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    networks:
      - rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  rabbitmq-consumer-service:
    build:
      context: .
      dockerfile: RabbitMQConsumerService/Dockerfile
    image: rabbitmq-consumer-service
    container_name: rabbitmq-consumer-service
    networks:
      - rabbitmq

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    networks:
      - kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  rabbitmq:
    external: true
  kafka:
    external: true