version: '3.4'

services:

  publisher-service:
    build:
      context: .
      dockerfile: PublisherService/Dockerfile
    image: publisher-service
    container_name: publisher-service
    ports:
      - 9000:80
      - 9100:443
    networks:
      - rabbitmq
      - kafka

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq

  rabbitmq-consumer-service:
    build:
      context: .
      dockerfile: RabbitMQConsumerService/Dockerfile
    image: rabbitmq-consumer-service
    container_name: rabbitmq-consumer-service
    networks:
      - rabbitmq

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka

  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka

  kafka-consumer-service:
    build:
      context: .
      dockerfile: KafkaConsumerService/Dockerfile
    image: kafka-consumer-service
    container_name: kafka-consumer-service
    networks:
      - kafka
      
networks:
  rabbitmq:
    name: rabbitmq
  kafka:
    name: kafka