version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    networks:
      - rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

networks:
  rabbitmq:
    external: true