version: '3.4'

services:

  kafka-consumer-service:
    build:
      context: .
      dockerfile: KafkaConsumerService/Dockerfile
    image: kafka-consumer-service
    container_name: kafka-consumer-service
    networks:
      - kafka
      
networks:
  kafka:
    external: true