version: '3.4'

services:
  publisher-service:
    build:
      context: .
    image: publisher-service
    container_name: publisher-service
    ports:
      - "9000:80"
      - "9100:443"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
      
networks:
  default:
    external: true
    name: message-broker-evaluation-network